
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hacker_clone_development

test:
  <<: *default
  database: hacker_clone_test


production:
  <<: *default
  database: hacker_clone_production
  username: hacker_clone
  password: <%= ENV['HACKER_CLONE_DATABASE_PASSWORD'] %>
